/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp_7.vista;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.LinkedHashMap;
import java.util.Map;

import javax.swing.JPanel;
import tp_7.entidades.Alumno;
import tp_7.entidades.Materia;

/**
 *
 * @author julie
 */
public class Colegio extends javax.swing.JFrame {

       public static Map<Integer,Alumno> alumnos=new LinkedHashMap();
    public static Map<Integer,Materia> materias=new LinkedHashMap();
    
    public Colegio() {
       initComponents();
       setSize(602, 490);
       Toolkit miPantalla= Toolkit.getDefaultToolkit();//Asi obtengo la pantalla
       Dimension tamanioPantalla=miPantalla.getScreenSize();//obtengo  la resolución de mi pantalla
       int alturaPantalla=tamanioPantalla.height;
       int anchoPantalla=tamanioPantalla.width;
       setLocation((anchoPantalla/2)-(602/2),(alturaPantalla/2)-(490/2));
       setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_addMateria = new javax.swing.JMenuItem();
        jMenuItem_addAlumno = new javax.swing.JMenuItem();
        jMenuItem_inscribir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 469, Short.MAX_VALUE)
        );

        jMenu2.setText("File");

        jMenuItem1.setText(" Alumnos/cantidad de materias");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Edit");

        jMenuItem_addMateria.setText("Agregar materia");
        jMenuItem_addMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_addMateriaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_addMateria);

        jMenuItem_addAlumno.setText("Agregar alumno");
        jMenuItem_addAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_addAlumnoActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_addAlumno);

        jMenuItem_inscribir.setText("Inscribir");
        jMenuItem_inscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_inscribirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_inscribir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearPanel(JPanel v){
        escritorio.removeAll();
        escritorio.repaint();
         escritorio.revalidate();
        v.setVisible(true);
        escritorio.add(v);
      
    }
    
    private void jMenuItem_addMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_addMateriaActionPerformed
        ViewAgregarMateria v=new ViewAgregarMateria();
        crearPanel(v);
       
    }//GEN-LAST:event_jMenuItem_addMateriaActionPerformed

    private void jMenuItem_addAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_addAlumnoActionPerformed
        ViewAgregarAlumno v=new ViewAgregarAlumno();
        crearPanel(v);
    }//GEN-LAST:event_jMenuItem_addAlumnoActionPerformed

    private void jMenuItem_inscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_inscribirActionPerformed
        ViewInscribir v=new ViewInscribir();
        crearPanel(v);
    }//GEN-LAST:event_jMenuItem_inscribirActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         ViewAlumnosCantidadMateria v=new ViewAlumnosCantidadMateria();
        crearPanel(v);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Colegio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem_addAlumno;
    private javax.swing.JMenuItem jMenuItem_addMateria;
    private javax.swing.JMenuItem jMenuItem_inscribir;
    // End of variables declaration//GEN-END:variables
}
