/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp_7.vista;

import controlador.Validaciones;
import java.awt.Color;
import javax.swing.JOptionPane;
import tp_7.entidades.Materia;

/**
 *
 * @author julie
 */
public class ViewAgregarMateria extends javax.swing.JPanel {

  private Validaciones v=new Validaciones(3); 
  
    public ViewAgregarMateria() {
        initComponents();
        setSize(592,429);
        jButton_guardar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_codigoMateria = new javax.swing.JTextField();
        errorCodigo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_materia = new javax.swing.JTextField();
        errorNombre = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_anio = new javax.swing.JTextField();
        errorAnio = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton_guardar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulario de materias");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CÓDIGO DE MATERIA:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 98, -1, -1));

        jTextField_codigoMateria.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jTextField_codigoMateria.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_codigoMateria.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField_codigoMateria.setText("ingrese el código(número)");
        jTextField_codigoMateria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_codigoMateriaFocusGained(evt);
            }
        });
        jTextField_codigoMateria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_codigoMateriaKeyReleased(evt);
            }
        });
        add(jTextField_codigoMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 98, 217, -1));

        errorCodigo.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        errorCodigo.setForeground(new java.awt.Color(255, 0, 0));
        errorCodigo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(errorCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 127, 390, 20));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("NOMBRE DE LA MATERIA:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 199, -1, -1));

        jTextField_materia.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jTextField_materia.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField_materia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_materiaFocusGained(evt);
            }
        });
        jTextField_materia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_materiaKeyReleased(evt);
            }
        });
        add(jTextField_materia, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 196, 292, -1));

        errorNombre.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        errorNombre.setForeground(new java.awt.Color(255, 0, 0));
        add(errorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 231, 490, 20));

        jLabel6.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jLabel6.setText("AÑO AL QUE PERTENECE:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 286, -1, -1));

        jTextField_anio.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jTextField_anio.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_anio.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField_anio.setText("número del 1-5");
        jTextField_anio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_anioFocusGained(evt);
            }
        });
        jTextField_anio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_anioKeyReleased(evt);
            }
        });
        add(jTextField_anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 287, 290, -1));

        errorAnio.setFont(new java.awt.Font("Calibri Light", 0, 12)); // NOI18N
        errorAnio.setForeground(new java.awt.Color(255, 0, 0));
        add(errorAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 316, 490, 20));

        jButton1.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, -1, -1));

        jButton2.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        jButton2.setText("Nuevo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, -1, -1));

        jButton_guardar.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        jButton_guardar.setText("Guardar");
        jButton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardarActionPerformed(evt);
            }
        });
        add(jButton_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_codigoMateriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_codigoMateriaKeyReleased
             
      v.soloNumeros(jTextField_codigoMateria.getText(),0);
      errorCodigo.setText(v.getError(0));
      jButton_guardar.setEnabled(v.validar());
   
           
    }//GEN-LAST:event_jTextField_codigoMateriaKeyReleased

    private void jTextField_codigoMateriaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_codigoMateriaFocusGained
        if(jTextField_codigoMateria.getText().equals("ingrese el código(número)"))
             jTextField_codigoMateria.setText("");
       jTextField_codigoMateria.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_jTextField_codigoMateriaFocusGained

    private void jTextField_materiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_materiaKeyReleased
        jTextField_materia.setText(jTextField_materia.getText().toUpperCase());
        v.validarTexto(jTextField_materia.getText(), 1);
        errorNombre.setText(v.getError(1));
        jButton_guardar.setEnabled(v.validar());
        
    }//GEN-LAST:event_jTextField_materiaKeyReleased

    private void jTextField_anioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_anioFocusGained
        if(jTextField_anio.getText().equals("número del 1-5"))
            jTextField_anio.setText("");
        jTextField_anio.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_jTextField_anioFocusGained

    private void jTextField_anioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_anioKeyReleased
       if( v.soloNumeros(jTextField_anio.getText(), 2))
             v.rango(jTextField_anio.getText(),2,1,5);
        errorAnio.setText(v.getError(2));
        jButton_guardar.setEnabled(v.validar());
    }//GEN-LAST:event_jTextField_anioKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextField_anio.setText("número del 1-5");
        jTextField_anio.setForeground(new Color(153,153,153));
        jTextField_codigoMateria.setText("ingrese el código(número)");
         jTextField_codigoMateria.setForeground(new Color(153,153,153));
        jTextField_materia.setText("");
        errorCodigo.setText("");
        errorNombre.setText("");
        errorAnio.setText("");
        v.initErrores();
        jButton_guardar.setEnabled(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField_materiaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_materiaFocusGained
       jTextField_materia.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_jTextField_materiaFocusGained

    private void jButton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardarActionPerformed
        int id=Integer.parseInt(jTextField_codigoMateria.getText());
       int anio=Integer.parseInt(jTextField_anio.getText());
       String nombre=jTextField_materia.getText();
       
       
           if(Colegio.materias.containsKey(id)){
                 int respuesta = JOptionPane.showConfirmDialog(null, "Esta materia ya se encuentra registrada, si hace click en \"si\"  cualquier modificación se guardará ¿Quieres hacer esto?", "Confirmar acción", JOptionPane.YES_NO_OPTION);
                 if (respuesta == JOptionPane.NO_OPTION) {
                       return;
                 } 
            } 
           
       Colegio.materias.put(id,new Materia(id,nombre,anio));
       JOptionPane.showMessageDialog(null,"Materia agregada");
     //  v.initErrores();
           
      
      
      
    }//GEN-LAST:event_jButton_guardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorAnio;
    private javax.swing.JLabel errorCodigo;
    private javax.swing.JLabel errorNombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField_anio;
    private javax.swing.JTextField jTextField_codigoMateria;
    private javax.swing.JTextField jTextField_materia;
    // End of variables declaration//GEN-END:variables
}
